### ISSUE TITLE
Naming a step

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-learneth-plugin#14]
According to this: https://remix-learneth-plugin.readthedocs.io/en/latest/setting_up_your_repository.html#name-of-a-step
A step's name is take from its folder name. 

**Problem:** when writing a tutorial - you need to edit the text in a step and sometimes you need to update the name of a step.  To do that you need to change a folder's name.  But changing a folder's name also can break the absolute links to the images in the folder. And I believe that the images need to have absolute links.

Also intuitively writing a tutorial is an explaining/ writing exercise - but changing a folder's name involves other sets of skills.  And furthermore - if a mistake in capitalization is made - in certain instances Git won't recognize this as change which can cause a tutorial's author to get a modest headache.

also this as a folder name is very ugly: 1._Interface_introduction

**Solution:**
the steps should be named in the .yml file.  Probably the steps are ordered in the .yml file too.

**Comment by bunsenstraat** [comment]
https://remix-learneth-plugin.readthedocs.io/en/latest/setting_up_your_repository.html#step-configuration
