### ISSUE TITLE
switching from a non learneth tab in the file explorer to a learneth tab or the other way around has probs

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-learneth-plugin#15]
I can't seem to select a learneth tab in the editor and get its contents to load in the editor

<img width="614" alt="image" src="https://user-images.githubusercontent.com/6050001/107565255-7a4a3880-6bb1-11eb-95e4-88d20ecda67b.png">

in this example step4.sol is selected but the Ballot contract is showing.

The files switch when I select show answer or Check Answer but not by clicking on a tab.

and when I select the file in the file explorer in the .learneth folder... it doesn't load either.

**Comment by ryestew** [comment]
This issue seems to be involved with tutorials named in the .yml file that include spaces
<img width="223" alt="image" src="https://user-images.githubusercontent.com/6050001/107698734-ffe9e900-6c82-11eb-9122-4bb59dc65002.png">

With tutorials like that - the file that gets loaded in the editor cannot be selected by its tab.


<img width="868" alt="image" src="https://user-images.githubusercontent.com/6050001/107697464-40e0fe00-6c81-11eb-8e38-4558ea8def04.png">

**Comment by ryestew** [comment]
When a tutorial doesn't load something into the editor - there isn't a problem.

**Comment by bunsenstraat** [comment]
wel spotted. It's not a learneth issue. I will make a new issue for the IDE.
