### ISSUE TITLE
Check step 5 of proxy contract

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-learneth-plugin#16]
When I paste the answer into the step5.sol file and run the test, I get this error:

```
Error: Error from IDE : Invalid input source specified.
```

**Comment by bunsenstraat** [comment]
I don't know what step5.sol is. @ryestew please clarify.

**Comment by ryestew** [comment]
This is in Intro to Solidity - on step 5 of that tutorial

**Comment by ryestew** [comment]
I just tested this issue again and didn't get that error.

**Comment by bunsenstraat** [comment]
cool
